# name: storybook deploy

# on:
#   push:
#     branches:
#       - develop

# env:
#   AZURE_WEBAPP_NAME: storybook-test_group # set this to your application's name
#   AZURE_WEBAPP_PACKAGE_PATH: "/docs-build" # set this to the path to your web app project, defaults to the repository root
#   NODE_VERSION: "14.x"

# jobs:
#   build-and-deploy:
#     name: Build and Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2.3.1
#       - name: Use Node.js ${{ env.NODE_VERSION }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ env.NODE_VERSION }}
#       - name: npm install, build, and test
#         run: |
#           # Build and test the project, then
#           # deploy to Azure Web App.
#           npm install
#           npm run build-storybook
#         working-directory: /
#       - name: "Deploy to Azure WebApp"
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#           package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

name: Build and Deploy Storybook
on:
  push:
    branches:
      - develop
env:
  AZURE_WEBAPP_NAME: storybook-test_group # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "docs-build"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: 🔧 Install dependencies
        run: npm i
      - name: 🏗 Build
        run: npm run build-storybook
      - name: 📁 Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs-build"
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_STONE_086AAE41E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write
  #   steps:
  #     - name: 🚀 Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1
